#!/bin/bash
#PBS -l nodes=1:ppn=14
#PBS -l walltime=80:00:00
#PBS -q long
#PBS -o /nlustre/users/nante/dothistroma/masters/mapping_genomes/mating_types/mating_types
#PBS -e /nlustre/users/nante/dothistroma/masters/mapping_genomes/mating_types/mating_types
#PBS -m abe
#PBS -M ruth.nante@fabi.up.ac.za
#PBS -N   blastp
cd $PBS_O_WORKDIR

module load    ncbi-blast-2.10.1+


#blastp the protein sequences

for f in *;
	do

if [ -d "$f" ];
	then
       #echo"$f is a directory"
    
cd $f

blastp -db ${f}.fasta -query /nlustre/users/nante/dothistroma/masters/mapping_genomes/mating_types/mating_types_fastas/Dsept1_2.fasta -out ${f}_sept1_2.txt

blastp -db ${f}.fasta -query /nlustre/users/nante/dothistroma/masters/mapping_genomes/mating_types/mating_types_fastas/Dsept1_1_1.fasta -out ${f}_sept1_1_1.txt

blastp -db ${f}.fasta -query /nlustre/users/nante/dothistroma/masters/mapping_genomes/mating_types/mating_types_fastas/Dpini1_2.fasta  -out ${f}_pini1_2.txt

blastp -db ${f}.fasta -query /nlustre/users/nante/dothistroma/masters/mapping_genomes/mating_types/mating_types_fastas/Dpini1_1_1.fasta  -out ${f}_pini1_1_1.txt

cd ..
fi
done






