#!/bin/bash
#PBS -l nodes=1:ppn=14
#PBS -l walltime=80:00:00
#PBS -qlong
#PBS -o /nlustre/users/nante/dothistroma/masters/mapping_genomes/mating_types/mating_types
#PBS -e /nlustre/users/nante/dothistroma/masters/mapping_genomes/mating_types/mating_types
#PBS -m abe
#PBS -M ruth.nante@fabi.up.ac.za
#PBS -N   makeblastdb

cd $PBS_O_WORKDIR

module load    ncbi-blast-2.10.1+

dir="/nlustre/users/nante/dothistroma/masters/mapping_genomes/mating_types/changed_index_fasta/change_line/"

while read Strain Mean SD;
do
base=$(basename $Strain "_R1.fastq.gz")

mkdir $base
cp $dir${base}.fasta $base
cd $base
makeblastdb -in ${base}.fasta  -parse_seqids -title "pini bd" -dbtype prot
cd ..

done < /nlustre/users/nante/dothistroma/masters/mapping_genomes/Assembly_all_masurca/Ruth_dothistroma_info_sheet.txt










